site_name: Grape
site_description: An automated RNAseq pipeline environment

repo_url: https://github.com/guigolab/grape

theme: mkdocs
theme_dir: mkdocs

copyright: >
  © Emilio Palumbo - <a href="http://big.crg.cat/computational_biology_of_rna_processing">GuigoLab</a> 
  @ <a href="http://www.crg.eu/">CRG</a>

pages:
- Home: index.md
- User guide:
    - Getting started: quickstart.md

markdown_extensions:
    - smarty
    - toc:
        permalink: 
    - sane_lists
    - admonition